#!/usr/bin/env bash
# =============================================================================
# GPAI — local one-shot installer (production-shape compose stack)
#
# Steps:
#   1. Verify Docker ≥ 24
#   2. Generate .env if missing (random POSTGRES_PASSWORD)
#   3. Build images (core, gateway, web)
#   4. Bring up postgres + redis (infra)
#   5. Run DB migrations via `docker compose run --rm migrate` for every
#      /migrations/*.sql file in lexical order. This replaces the
#      brief's broken step (which used `docker compose exec -T core sh -c`
#      and never executed any SQL).
#   6. Bring up core / ingestor / gateway / web
#   7. Wait for gateway and web to respond on the loopback health probes
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
COMPOSE_FILE="${REPO_ROOT}/deploy/docker-compose.yml"

cd "${REPO_ROOT}"

# -----------------------------------------------------------------------------
# 1. Check Docker
# -----------------------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  echo "✗ Docker 未安装"; exit 1
fi

DOCKER_VERSION=$(docker version --format '{{.Server.Version}}' 2>/dev/null || echo "0.0.0")
NEEDED="24.0"
if [ "$(printf '%s\n' "${NEEDED}" "${DOCKER_VERSION}" | sort -V | head -n1)" != "${NEEDED}" ]; then
  echo "✗ Docker 需 ≥ ${NEEDED}(当前 ${DOCKER_VERSION})"; exit 1
fi

# -----------------------------------------------------------------------------
# 2. Generate .env if missing
# -----------------------------------------------------------------------------
if [ ! -f "${REPO_ROOT}/.env" ]; then
  PASSWORD=$(openssl rand -base64 24 | tr -d '=+/' | head -c 32)
  cat > "${REPO_ROOT}/.env" <<EOF
# Generated by deploy/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
POSTGRES_PASSWORD=${PASSWORD}
GATEWAY_URL=http://localhost:8080
INGESTOR_POLL_SECS=30
INGESTOR_INSTRUMENTS=US.AAPL.NASDAQ
RUST_LOG=info
EOF
  echo "✓ 已生成 .env(密码已写入 ${REPO_ROOT}/.env)"
fi

set -a
# shellcheck disable=SC1091
source "${REPO_ROOT}/.env"
set +a

if [ -z "${POSTGRES_PASSWORD:-}" ]; then
  echo "✗ POSTGRES_PASSWORD 未设置(.env 损坏?)"; exit 1
fi

# -----------------------------------------------------------------------------
# 3. Build images
# -----------------------------------------------------------------------------
echo "→ 构建 core 镜像..."
docker build -t gpai/core:latest    -f services/core/Dockerfile   "${REPO_ROOT}"

echo "→ 构建 gateway 镜像..."
docker build -t gpai/gateway:latest -f apps/gateway/Dockerfile   "${REPO_ROOT}"

echo "→ 构建 web 镜像..."
docker build -t gpai/web:latest     -f apps/web/Dockerfile       "${REPO_ROOT}"

# -----------------------------------------------------------------------------
# 4. Bring up infra
# -----------------------------------------------------------------------------
echo "→ 启动 postgres + redis..."
docker compose -f "${COMPOSE_FILE}" up -d postgres redis

echo "→ 等待 postgres / redis 就绪..."
for i in $(seq 1 60); do
  PG_OK=$(docker compose -f "${COMPOSE_FILE}" exec -T postgres pg_isready -U gpai -d gpai 2>/dev/null || true)
  RD_OK=$(docker compose -f "${COMPOSE_FILE}" exec -T redis    redis-cli ping   2>/dev/null | grep -c PONG || true)
  if [[ "${PG_OK}" == *"accepting connections"* ]] && [ "${RD_OK}" -ge 1 ]; then
    break
  fi
  sleep 2
done

# -----------------------------------------------------------------------------
# 5. Run DB migrations via one-shot migrate service
# -----------------------------------------------------------------------------
echo "→ 运行数据库迁移..."
shopt -s nullglob
MIGRATIONS=( "${REPO_ROOT}/db/migrations"/*.sql )
shopt -u nullglob
if [ "${#MIGRATIONS[@]}" -eq 0 ]; then
  echo "  (db/migrations/ 下未找到 .sql 文件,跳过)"
else
  for sql in "${MIGRATIONS[@]}"; do
    fname=$(basename "${sql}")
    echo "  · ${fname}"
    docker compose -f "${COMPOSE_FILE}" run --rm migrate \
      psql -h postgres -U gpai -d gpai -v ON_ERROR_STOP=1 -f "/migrations/${fname}"
  done
fi

# -----------------------------------------------------------------------------
# 6. Bring up application services
# -----------------------------------------------------------------------------
echo "→ 启动 core / ingestor / gateway / web..."
docker compose -f "${COMPOSE_FILE}" up -d core ingestor gateway web

# -----------------------------------------------------------------------------
# 7. Wait for public endpoints
# -----------------------------------------------------------------------------
echo "→ 等待 gateway 与 web 就绪..."
for i in $(seq 1 60); do
  if curl -sf http://localhost:8080/healthz >/dev/null 2>&1 \
     || curl -sf http://localhost:8080/        >/dev/null 2>&1; then
    GATEWAY_OK=1
  else
    GATEWAY_OK=0
  fi
  if curl -sf http://localhost:3000/ >/dev/null 2>&1; then
    WEB_OK=1
  else
    WEB_OK=0
  fi
  if [ "${GATEWAY_OK}" -eq 1 ] && [ "${WEB_OK}" -eq 1 ]; then
    break
  fi
  sleep 2
done

echo ""
echo "✓ GPAI 已启动"
echo "  Web:      http://localhost:3000"
echo "  Gateway:  http://localhost:8080"
echo "  AAPL 页:  http://localhost:3000/markets/US.AAPL.NASDAQ"